# Generated by Django 5.0.3 on 2024-03-26 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_real_name_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999999)]),
        ),
    ]
