# Generated by Django 5.0.3 on 2024-03-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_gender_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
