# Generated by Django 5.0.3 on 2024-03-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_user_gender_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='lasts_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
