# Generated by Django 5.0.3 on 2024-04-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_wallet_user_alter_purchase_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
