# Generated by Django 5.0.3 on 2024-04-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_wallet_user_alter_purchase_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
    ]
