# Generated by Django 5.0.3 on 2024-04-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.purchase'),
        ),
    ]
