# Generated by Django 5.0.3 on 2024-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
