# Generated by Django 5.0.3 on 2024-04-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_purchase_purchase_is_returned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
